FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY vendor/ ./vendor/
COPY fileserver/ ./fileserver/
COPY proxy/ ./proxy/
COPY main.go ./
RUN go build -mod=vendor -o fileserverbin ./fileserver/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/fileserverbin .
RUN mkdir -p /app/files
EXPOSE 8082
CMD ["./fileserverbin"]