FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY vendor/ ./vendor/
COPY . .
RUN go build -mod=vendor -o proxybin .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/proxybin .
EXPOSE 9090
CMD ["./proxybin"]